services:
  db:
    image: bitnami/postgresql:latest
    container_name: brevly_db
    restart: unless-stopped
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - ./docker:/docker-entrypoint-initdb.d
      - db:/var/lib/postgresql/data
    networks:
      - brevly
      - db

  brevly:
    build: .
    depends_on:
      - db
    restart: unless-stopped
    container_name: brevly_server
    expose:
      - $PORT
    environment:
      - $PORT:$PORT
      - BASE_URL:$BASE_URL
      - DATABASE_URL=$DATABASE_URL
      - CLOUDFLARE_ACCOUNT_ID=$CLOUDFLARE_ACCOUNT_ID
      - CLOUDFLARE_ACCESS_KEY_ID=$CLOUDFLARE_ACCESS_KEY_ID
      - CLOUDFLARE_SECRET_ACCESS_KEY=$CLOUDFLARE_SECRET_ACCESS_KEY
      - CLOUDFLARE_BUCKET=$CLOUDFLARE_BUCKET
      - CLOUDFLARE_PUBLIC_URL=$CLOUDFLARE_PUBLIC_URL
    network_mode: host

volumes:
  db:

networks:
  brevly:
    driver: bridge
  db:
    driver: bridge