name: brevly

services:
  pg:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=brevly

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3333:3333'
    environment:
      - PORT=3333
      - API_URL=http://localhost:3333
      - DATABASE_URL=postgresql://docker:docker@pg:5432/brevly
      - CLOUDFLARE_ACCOUNT_ID=
      - CLOUDFLARE_ACCESS_KEY_ID=
      - CLOUDFLARE_SECRET_ACCESS_KEY=
      - CLOUDFLARE_BUCKET=
      - CLOUDFLARE_PUBLIC_URL=